"""initial schema

Revision ID: 35b4c4c61510
Revises: 
Create Date: 2025-06-05 09:29:18.835871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35b4c4c61510'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('job_type_filter', sa.String(), nullable=True),
    sa.Column('target_url_pattern', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('comparison_operator', sa.String(), nullable=True),
    sa.Column('anomaly_type_filter', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('notification_channels', postgresql.ARRAY(String()), nullable=True),
    sa.Column('notification_recipients', postgresql.ARRAY(String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_gap_analysis_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('competitor_urls', postgresql.ARRAY(String()), nullable=True),
    sa.Column('missing_topics', postgresql.ARRAY(String()), nullable=True),
    sa.Column('missing_keywords', postgresql.ARRAY(String()), nullable=True),
    sa.Column('content_format_gaps', postgresql.ARRAY(String()), nullable=True),
    sa.Column('actionable_insights', postgresql.ARRAY(String()), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_gap_analysis_results_target_url'), 'content_gap_analysis_results', ['target_url'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('started_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('urls_discovered', sa.Integer(), nullable=True),
    sa.Column('urls_crawled', sa.Integer(), nullable=True),
    sa.Column('links_found', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('anomalies_detected', postgresql.ARRAY(String()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('cron_schedule', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('whois_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('referring_domains', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=False)
    op.create_table('keyword_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seed_keyword', sa.String(), nullable=False),
    sa.Column('suggested_keyword', sa.String(), nullable=False),
    sa.Column('search_volume_monthly', sa.Integer(), nullable=True),
    sa.Column('cpc_estimate', sa.Float(), nullable=True),
    sa.Column('keyword_trend', postgresql.ARRAY(Float()), nullable=True),
    sa.Column('competition_level', sa.String(), nullable=True),
    sa.Column('data_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_keyword', 'suggested_keyword', name='_seed_suggested_uc')
    )
    op.create_index(op.f('ix_keyword_suggestions_seed_keyword'), 'keyword_suggestions', ['seed_keyword'], unique=False)
    op.create_index(op.f('ix_keyword_suggestions_suggested_keyword'), 'keyword_suggestions', ['suggested_keyword'], unique=False)
    op.create_table('link_prospects',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reasons', postgresql.ARRAY(String()), nullable=True),
    sa.Column('contact_info', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_outreach_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_link_prospects_url'), 'link_prospects', ['url'], unique=False)
    op.create_table('outreach_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_domain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('target_identifier', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('started_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('cron_schedule', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serp_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('result_url', sa.String(), nullable=False),
    sa.Column('title_text', sa.String(), nullable=False),
    sa.Column('snippet_text', sa.Text(), nullable=True),
    sa.Column('rich_features', postgresql.ARRAY(String()), nullable=True),
    sa.Column('page_load_time', sa.Float(), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'result_url', name='_keyword_result_uc')
    )
    op.create_index(op.f('ix_serp_results_keyword'), 'serp_results', ['keyword'], unique=False)
    op.create_table('social_mentions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('mention_url', sa.String(), nullable=False),
    sa.Column('mention_text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mention_url')
    )
    op.create_index(op.f('ix_social_mentions_query'), 'social_mentions', ['query'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('backlinks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('source_domain_name', sa.String(), nullable=False),
    sa.Column('target_domain_name', sa.String(), nullable=False),
    sa.Column('anchor_text', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('rel_attributes', postgresql.ARRAY(String()), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('position_on_page', sa.Integer(), nullable=True),
    sa.Column('is_image_link', sa.Boolean(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(), nullable=True),
    sa.Column('last_seen_date', sa.DateTime(), nullable=True),
    sa.Column('authority_passed', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('spam_level', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_domain_metrics', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_domain_name'], ['domains.name'], ),
    sa.ForeignKeyConstraint(['target_domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'target_url', name='_source_target_uc')
    )
    op.create_table('domain_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('referring_domains', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name', 'snapshot_date', name='_domain_snapshot_uc')
    )
    op.create_index(op.f('ix_domain_history_domain_name'), 'domain_history', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_history_snapshot_date'), 'domain_history', ['snapshot_date'], unique=False)
    op.create_table('domain_intelligence',
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('total_social_mentions', sa.Integer(), nullable=True),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
    sa.Column('top_social_platforms', postgresql.ARRAY(String()), nullable=True),
    sa.Column('avg_content_quality_score', sa.Float(), nullable=True),
    sa.Column('content_gaps_identified', sa.Integer(), nullable=True),
    sa.Column('avg_performance_score', sa.Float(), nullable=True),
    sa.Column('avg_accessibility_score', sa.Float(), nullable=True),
    sa.Column('broken_links_ratio', sa.Float(), nullable=True),
    sa.Column('estimated_traffic_trend', postgresql.ARRAY(Float()), nullable=True),
    sa.Column('competitor_overlap_score', sa.Float(), nullable=True),
    sa.Column('social_data_summary', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('content_data_summary', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('technical_data_summary', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('domain_name')
    )
    op.create_index(op.f('ix_domain_intelligence_domain_name'), 'domain_intelligence', ['domain_name'], unique=False)
    op.create_table('link_profiles',
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('target_domain_name', sa.String(), nullable=False),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('unique_domains', sa.Integer(), nullable=True),
    sa.Column('dofollow_links', sa.Integer(), nullable=True),
    sa.Column('nofollow_links', sa.Integer(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('anchor_text_distribution', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('referring_domains', postgresql.ARRAY(String()), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('target_url')
    )
    op.create_index(op.f('ix_link_profiles_target_url'), 'link_profiles', ['target_url'], unique=False)
    op.create_table('outreach_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_url', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['outreach_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('crawl_status', sa.String(), nullable=True),
    sa.Column('crawl_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=False)
    op.create_table('seo_metrics',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('page_size_bytes', sa.Integer(), nullable=True),
    sa.Column('title_length', sa.Integer(), nullable=True),
    sa.Column('meta_description_length', sa.Integer(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=True),
    sa.Column('h2_count', sa.Integer(), nullable=True),
    sa.Column('internal_links', sa.Integer(), nullable=True),
    sa.Column('external_links', sa.Integer(), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('images_without_alt', sa.Integer(), nullable=True),
    sa.Column('has_canonical', sa.Boolean(), nullable=True),
    sa.Column('has_robots_meta', sa.Boolean(), nullable=True),
    sa.Column('has_schema_markup', sa.Boolean(), nullable=True),
    sa.Column('broken_links', postgresql.ARRAY(String()), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('audit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('issues', postgresql.ARRAY(String()), nullable=True),
    sa.Column('structured_data_types', postgresql.ARRAY(String()), nullable=True),
    sa.Column('og_title', sa.String(), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('twitter_title', sa.String(), nullable=True),
    sa.Column('twitter_description', sa.Text(), nullable=True),
    sa.Column('validation_issues', postgresql.ARRAY(String()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('nlp_entities', postgresql.ARRAY(String()), nullable=True),
    sa.Column('nlp_sentiment', sa.String(), nullable=True),
    sa.Column('nlp_topics', postgresql.ARRAY(String()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url'], ['urls.url'], ),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_metrics')
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_table('urls')
    op.drop_table('outreach_events')
    op.drop_index(op.f('ix_link_profiles_target_url'), table_name='link_profiles')
    op.drop_table('link_profiles')
    op.drop_index(op.f('ix_domain_intelligence_domain_name'), table_name='domain_intelligence')
    op.drop_table('domain_intelligence')
    op.drop_index(op.f('ix_domain_history_snapshot_date'), table_name='domain_history')
    op.drop_index(op.f('ix_domain_history_domain_name'), table_name='domain_history')
    op.drop_table('domain_history')
    op.drop_table('backlinks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_social_mentions_query'), table_name='social_mentions')
    op.drop_table('social_mentions')
    op.drop_index(op.f('ix_serp_results_keyword'), table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_table('report_jobs')
    op.drop_table('outreach_campaigns')
    op.drop_index(op.f('ix_link_prospects_url'), table_name='link_prospects')
    op.drop_table('link_prospects')
    op.drop_index(op.f('ix_keyword_suggestions_suggested_keyword'), table_name='keyword_suggestions')
    op.drop_index(op.f('ix_keyword_suggestions_seed_keyword'), table_name='keyword_suggestions')
    op.drop_table('keyword_suggestions')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_content_gap_analysis_results_target_url'), table_name='content_gap_analysis_results')
    op.drop_table('content_gap_analysis_results')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
