"""Add last_fetched_at to alert_rules

Revision ID: 81269013ea33
Revises: 20240730143000
Create Date: 2025-06-08 04:58:21.082767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81269013ea33'
down_revision: Union[str, None] = '20240730143000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_performance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('links_extracted', sa.Integer(), nullable=True),
    sa.Column('crawl_speed_pages_per_minute', sa.Float(), nullable=True),
    sa.Column('success_rate_percentage', sa.Float(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('cpu_utilization_percent', sa.Float(), nullable=True),
    sa.Column('memory_utilization_percent', sa.Float(), nullable=True),
    sa.Column('network_io_mbps', sa.Float(), nullable=True),
    sa.Column('errors_logged', sa.Integer(), nullable=True),
    sa.Column('bottlenecks_detected', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_performance_logs_satellite_id'), 'satellite_performance_logs', ['satellite_id'], unique=False)
    op.add_column('alert_rules', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('backlinks', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('content_gap_analysis_results', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('domain_history', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('domain_intelligence', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('domains', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('keyword_suggestions', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('link_profiles', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('link_prospects', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('outreach_campaigns', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('outreach_events', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('report_jobs', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('seo_metrics', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('serp_results', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('social_mentions', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('urls', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_fetched_at')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'role')
    op.drop_column('urls', 'last_fetched_at')
    op.drop_column('social_mentions', 'last_fetched_at')
    op.drop_column('serp_results', 'last_fetched_at')
    op.drop_column('seo_metrics', 'last_fetched_at')
    op.drop_column('report_jobs', 'last_fetched_at')
    op.drop_column('outreach_events', 'last_fetched_at')
    op.drop_column('outreach_campaigns', 'last_fetched_at')
    op.drop_column('link_prospects', 'last_fetched_at')
    op.drop_column('link_profiles', 'last_fetched_at')
    op.drop_column('keyword_suggestions', 'last_fetched_at')
    op.drop_column('domains', 'last_fetched_at')
    op.drop_column('domain_intelligence', 'last_fetched_at')
    op.drop_column('domain_history', 'last_fetched_at')
    op.drop_column('crawl_jobs', 'last_fetched_at')
    op.drop_column('content_gap_analysis_results', 'last_fetched_at')
    op.drop_column('backlinks', 'last_fetched_at')
    op.drop_column('alert_rules', 'last_fetched_at')
    op.drop_index(op.f('ix_satellite_performance_logs_satellite_id'), table_name='satellite_performance_logs')
    op.drop_table('satellite_performance_logs')
    # ### end Alembic commands ###
