"""Add role and organization_id to users table

Revision ID: xxxxxxxxxxxx
Revises: <previous_revision_id>
Create Date: 2024-06-07 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'xxxxxxxxxxxx'
down_revision = '<previous_revision_id>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='customer'))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
