# Link_Profiler/config/monitoring.yaml

monitoring:
  monitor_port: 8001 # Port for the separate monitoring dashboard (if used)
  monitor_auth:
    username: "monitor_user"
    password: "${LP_MONITOR_PASSWORD}" # Loaded from environment variable
  crawler_timeout: 30 # Seconds without heartbeat before considering a crawler dead
  performance_window: 60 # Time window in seconds for calculating throughput metrics
  failed_jobs_threshold: 10 # Number of failed jobs in 24h to trigger critical alert
  failed_jobs_warning_threshold: 5 # Number of failed jobs in 24h to trigger warning alert
