# Security Configuration
# Circuit Breaker settings
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: 60
  success_threshold: 3
  timeout_duration: 30
  redis_key_prefix: "cb_state:"

# Rate Limiting settings
rate_limiting:
  ml_enhanced: true
  min_delay: 0.1
  max_delay: 30.0
  learning_rate: 0.1
  aggression_factor: 0.8

# Connection Optimization settings
connection_optimization:
  max_connections: 250
  max_connections_per_host: 25
  timeout_total: 30
  timeout_connect: 10
  timeout_sock_read: 30
  retry_attempts: 3
  retry_delay_base: 0.5
  connection_health_check: true

# Advanced Session Manager settings
advanced_session_manager:
  enabled: true
  initial_pool_size: 10
  max_pool_size_per_domain: 25
  adaptation_interval: 45

# Technical Auditor
technical_auditor:
  lighthouse_path: "lighthouse"
  ssl_labs_api:
    enabled: false
    base_url: "https://api.ssllabs.com/api/v3/analyze"
  security_trails_api:
    enabled: false
    api_key: "${LP_SECURITY_TRAILS_API_KEY}"
    base_url: "https://api.securitytrails.com/v1"
  technical_auditor_service:
    allow_live: true
    staleness_threshold_hours: 72

# Social Media API Security
social_media_crawler:
  twitter_api_key: "${LP_TWITTER_API_KEY}"
  twitter_api_secret: "${LP_TWITTER_API_SECRET}"
  twitter_bearer_token: "${LP_TWITTER_BEARER_TOKEN}"
  facebook_app_id: "${LP_FACEBOOK_APP_ID}"
  facebook_app_secret: "${LP_FACEBOOK_APP_SECRET}"
  linkedin_client_id: "${LP_LINKEDIN_CLIENT_ID}"
  linkedin_client_secret: "${LP_LINKEDIN_CLIENT_SECRET}"
  reddit_api:
    enabled: false
    client_id: "${LP_REDDIT_CLIENT_ID}"
    client_secret: "${LP_REDDIT_CLIENT_SECRET}"
    user_agent: "LinkProfilerBot/1.0"
  youtube_api:
    enabled: false
    api_key: "${LP_YOUTUBE_API_KEY}"
    base_url: "https://www.googleapis.com/youtube/v3"
  news_api:
    enabled: false
    api_key: "${LP_NEWS_API_KEY}"
    base_url: "https://newsapi.org/v2"
  social_media_service:
    allow_live: true
    staleness_threshold_hours: 24

# Web3 Security
web3_service:
  allow_live: true
  staleness_threshold_hours: 24
  blockchain_node_url: "https://mainnet.infura.io/v3/${LP_INFURA_PROJECT_ID}"
  etherscan_api_key: "${LP_ETHERSCAN_API_KEY}"
  opensea_api_key: "${LP_OPENSEA_API_KEY}"

# Historical Data Integration
historical_data:
  wayback_machine_api:
    enabled: false
    base_url: "http://web.archive.org/cdx/search/cdx"
  common_crawl_api:
    enabled: false
    base_url: "https://index.commoncrawl.org"
  wayback_machine_client:
    allow_live: true
    staleness_threshold_hours: 168

# Local SEO Integration
local_seo:
  nominatim_api:
    enabled: false
    base_url: "https://nominatim.openstreetmap.org/search"
    user_agent: "LinkProfilerApp/1.0 (your_email@example.com)"
