apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: link-profiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: linkprofiler/coordinator:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/link_profiler_db"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
  namespace: link-profiler
spec:
  selector:
    app: coordinator
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer````

Link_Profiler\deployment\kubernetes\k8s-satellites.yaml
