apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-crawlers
  namespace: link-profiler
spec:
  replicas: 3  # Start with 3 satellites, can be scaled
  selector:
    matchLabels:
      app: satellite-crawler
  template:
    metadata:
      labels:
        app: satellite-crawler
    spec:
      containers:
      - name: satellite
        image: linkprofiler/satellite:latest
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: REGION
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  # Use node name as region
        - name: CRAWLER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Use pod name as crawler ID
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import redis; r=redis.Redis.from_url('redis://redis-service:6379'); r.ping()"
          initialDelaySeconds: 30
          periodSeconds: 30